apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: gsm-lab
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80